### ISSUE TITLE
is it GPU running?

### ISSUE THREAD

**Issue by chikiuso** [GuardatiSimone/pistoBot#3]
hi I tried your colab work but it running really slow, is it cuda (gpu) enabled? I run the pretrained one (gpt2-simple), thanks

**Comment by pistocop** [comment]
Hi @chikiuso,
Yes the colab notebook is set to use the GPU. 

You can see it on the first command of the notebook:
`!nvidia-smi # p100 suggested`
This command shows some information about the GPU, including the type.

Colaboratory could start with different GPU type, and the P100 should be the one with the best performances, for more info see the [official website](https://research.google.com/colaboratory/faq.html).
If you want to try for a different GPU, go to Runtime -> Factory Reset Runtime.

Anyway, I don't know how big is your dataset, but the GPT-2 model used is heavy and requires a lot of time and resources, so training may keep >8h.
