### ISSUE TITLE
Google Colab: No pytorch_model.bin found 

### ISSUE THREAD

**Issue by HuskyCodez** [GuardatiSimone/pistoBot#5]
![image](https://user-images.githubusercontent.com/64391668/123499401-05abfe00-d669-11eb-8c5a-cabc475de066.png)

after training the model i tried to load it and confirmed pytorch model exists but it won't run? any solution?

**Comment by pistocop** [comment]
Hi @HuskyCodez,

I have just tested the code and in my case no error was raised.

In the screenshot I have done there are some checks you can do:
1. Be sure the training has completed correctly
2. Check the .bin file position
3. Check the loading path, in your example, there is a "/" on the path prefix, have you changed any line of the original code?

Another possible problem could be the Colab ephemeral runtime, after some time of inactivity or a maximum running time, Colab VM is restarted and everything stored in the machine is wiped. 
One another possible thing is that your model was wiped with the VM restart.

Let me know if any of those tips can help you.

![2021-06-26_13-05](https://user-images.githubusercontent.com/31094729/123511077-8c6bd580-d67f-11eb-86b7-7276704bbed8.png)
